### ISSUE TITLE
Schedule datetime is not always what has been entered 

### ISSUE THREAD

**Issue by xpillons** [realsail-net/feature-requests#8]
## Version

0.3.21

## Expected Behavior

When I manually enter a date time like 10:55 I want my action to be registered at that exact time.

## Actual Behavior

Sometimes, instead of 10:55 it is registered as 10:54. This is probably because of the rounding of the hours field. If you enter a value in the datetime field this one should be taken in priority.

**Comment by realsailnet** [comment]
The issue was solved on version 1.0.0. The UI was rounding the hours field incorrectly
